Step3
code-squad/java-ladder pull request #29
Opened 2018-03-13 13:00 UTC by sarguments

2018-03-13 23:55 UTC, javajigi requested changes
UI 로직과 비지니스 로직을 분리할 수 있도록 조금만 더 노력하면 좋겠다.

2018-03-13 23:55 UTC, javajigi commented on src/main/java/saru/InputUtil.java
>          return userNum * 2 - 1;
2, 1도 무엇을 의미하는지 상수 값으로 만들면 좋겠음.

2018-03-13 23:55 UTC, javajigi commented on src/main/java/saru/LadderGame.java
> +        OutputUtil.printLadderAndNames(this.names, this.getLadderLines());
InputUtil, OutputUtil을 이곳에서 사용하지 않고 구현할 수 없을까?
UI 로직과 비지니스 로직을 분리한다.

2018-03-13 23:55 UTC, javajigi commented on src/main/java/saru/LadderGame.java
> +        String[] nameArr = InputUtil.getUserName();
InputUtil 통해 받지 말고 외부에서 받은 후 생성자를 통해 전달해 본다.

2018-03-13 23:55 UTC, javajigi commented on src/main/java/saru/Line.java
> +                checkPointHasInterLine(index - 2)) {
여기 if문이 상당히 복잡한데 좀 더 쉽게 구현할 수 있는 방법은 없을까?

2018-03-13 23:55 UTC, javajigi commented on src/main/java/saru/Line.java
> +        return isLineExist;
이런 코드는 한 라인으로 구현해도 되지 않을까?

2018-03-14 01:59 UTC, sarguments commented on src/main/java/saru/InputUtil.java
>          return userNum * 2 - 1;
식 자체를 상수화 할 수 있나요? 2, 1 따로는 상수화 하기가 애매한 것 같습니다

2018-03-14 13:34 UTC, merged