Step5
code-squad/java-ladder pull request #37
Opened 2018-03-15 09:16 UTC by imjinbro

[변경한 부분]
1. 컨트롤러에서 기준값만 전달해주고 입력에 요청을 해서 기준에 맞지않으면 에러메세지 출력하고 정상적인 값 받아오도록 변경
2. 이름과 결과 매핑, 매핑 결과 메세지 빌더 구현
3. 매핑한 결과를 가지고 검색 싸이클 구현 : 이름 혹은 all
4. 뷰에 매핑 결과와 이름을 전달하면 자기에게 맞는 메세지를 빌드 할 수 있도록 구현, 사다리만 출력하는 것도 뷰에서 만들도록 변경
4. 매핑 과정에서 이동하는 과정 테스트 코드 작성
5. String -> 클래스로 감싸기
6. 커밋 쪼개서 푸시하기

2018-03-15 11:38 UTC, javajigi requested changes
오늘 수업 중 다룬 내용을 바로 적용한 모습이 인상적이네요. 앞으로도 기대되네요.

2018-03-15 11:38 UTC, javajigi commented on src/main/java/domain/LadderMatcher.java
> +        }
로직을 이해하기 쉽지 않은데 좀 더 쉽게 구현할 수 있는 방법은 없을까?

2018-03-15 11:38 UTC, javajigi commented on src/main/java/domain/LadderMatcher.java
> +        return ladder.getHeight() <= currentHeightIdx;
ladder.isFinishSearch(currentHeightIdx)

객체에게 묻지 말고 말하라.(메시지를 보내라.)

2018-03-15 11:38 UTC, javajigi commented on src/main/java/domain/LadderMatcher.java
> +        while (canMove(line, currentPosition + 1)) {
line.canMove(currentPosition + 1)은 안되나?

2018-03-15 11:38 UTC, javajigi commented on src/main/java/domain/Results.java
> +        }
자바8 stream의 filter() 메소드 활용해 구현해 본다.

2018-03-15 11:38 UTC, javajigi commented on src/main/java/domain/Name.java
> +        this.name = name;
name 값이 유효한지 체크하는 로직을 이곳에 구현하면 어떨까?

2018-03-15 11:38 UTC, javajigi commented on src/main/java/domain/Result.java
> +    Result(Name name, Reward reward) {
`String name, String reward`로 구현해 생성자에서 new Name(name), new Reward(reward)로 구현한다면..

2018-03-15 11:38 UTC, javajigi commented on src/test/java/view/InputTest.java
> +        assertEquals(false, Input.isInvalidPlayerNum(MIN_PLAYER_NUM, 3));
assertFalse()롤 사용할 수도 있음.
또는 assertThat( is())도 가능.

2018-03-16 08:04 UTC, imjinbro commented
푸시하고 힌트보면서 코드 비교해보니 객체지향적이지 않은 코드들이 많이보이네요.... 구현할 때 더 많이 생각하면서 구현을 해야겠습니다.

2018-03-16 08:10 UTC, javajigi requested changes
5단계 힌트에 제가 구현한 코드와 본인의 코드를 비교해보고 적용할 부분이 있다면 적용해 본다. 피드백 하나 남겼어요.

2018-03-16 08:10 UTC, javajigi commented on src/main/java/domain/Names.java
> +        return false;
HashSet 이용해 해결해 본다.

2018-03-18 11:46 UTC, merged