Step5
code-squad/java-ladder pull request #42
Opened 2018-03-16 07:52 UTC by krapeaj

Player, Prize, Result 클래스 추가
5단계 최초 PR

2018-03-16 08:00 UTC, javajigi requested changes
피드백 내용 반영해 보고요. 반영한 후에 제가 5단계 힌트로 준 내용도 참고해 리팩토링해 보면 좋겠네요.

2018-03-16 08:00 UTC, javajigi commented on src/main/java/ladder/LadderGameConsole.java
> +        return ladderGame;
로직 구현과 View 로직이 분리됐네요 👍

2018-03-16 08:00 UTC, javajigi commented on src/main/java/ladder/LadderGameConsole.java
> +        return prizes;
값을 입력받고 처리하는 코드와 main() 메소드도 서로 다른 클래스로 분리하는 것은 어떨까요?

2018-03-16 08:00 UTC, javajigi commented on src/main/java/ladder/domain/Item.java
> +    String getName();
오호. interface를 쓴 이유는?

2018-03-16 08:00 UTC, javajigi commented on src/main/java/ladder/domain/LadderGame.java
> +    public Map<String, String> generateResult() {
오호. Map까지 알아서 사용했군요 💯

2018-03-16 08:00 UTC, javajigi commented on src/main/java/ladder/domain/Player.java
> +    }
인스턴스 변수는 있는데 이 인스턴스 변수와 관련된 로직이 없어 좀 아쉽네요.
혹시 관련된 로직은 없을까요?

2018-03-16 08:00 UTC, javajigi commented on src/main/java/ladder/domain/Result.java
> +    }
moveLeft와 moveRight를 Row 객체가 담당하도록 구현하면 어떨까요?
Row가 담당하면 어떻게 될까요? 어느 곳에 구현하는 것이 나을까요?

2018-03-16 08:00 UTC, javajigi commented on src/main/java/ladder/domain/Result.java
> +public class Result {
이 클래스 로직이 핵심 로직인 것 같은데 테스트 코드가 없어 아쉽네요.

2018-03-16 13:36 UTC, krapeaj commented on src/main/java/ladder/domain/Item.java
> +    String getName();
StringBuilder로 사다리를 지을 때 빌더를 크게 세 가지로 나눴습니다: 참여자 이름 빌더, 사다리 빌더, 상품 빌더.
이 중에 이름과 상품은 둘 다 같은 수의 이름을 가지고 있어서 같은 방식으로 StringBuilder를 구현하게 되는데, 인자만 다르고 거의 비슷한 내용의 메소드를 두 개 만드는 것 보다 하나의 메소드로 구현하는 게 중복을 제거하는 측면에서 더 낫지 않을까 싶어서 방법을 찾다가 써봤습니다. 메소드가 인자로 스트링을 받지 않고 객체를 받아서 인터페이스까지 가게 됐습니다..

2018-03-18 11:56 UTC, javajigi requested changes
테스트 코드 깔끔하게 구현 잘 했네요. 피드백 몇 개 남겨요.

2018-03-18 11:56 UTC, javajigi commented on src/main/java/ladder/domain/Direction.java
> +        return new Direction("down");
Direction 초기화하는 부분을 좀 더 단순화할 수는 없을까?
5단계 힌트의 Direction 참고.
굳이 right, left 값을 가질 필요가 있을까?

2018-03-18 11:56 UTC, javajigi commented on src/main/java/ladder/domain/Player.java
> +        if (direction.equals("left")) {
Direction을 인자로 전달해 direction.isLeft(), direction.isRight()와 같이 구현할 수는 없을까?

2018-03-18 11:56 UTC, javajigi commented on src/main/java/ladder/domain/Point.java
> +        return "down";
String으로 변환하지 말고 Direction을 반환하면 안되나?

2018-03-19 02:49 UTC, merged